/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InnButton {
        "autofocus": boolean;
        "circle": boolean;
        "color": string;
        "customClass": string;
        "disabled": boolean;
        "ghost": boolean;
        "icon": string;
        "iconPosition": 'left' | 'right';
        "loading": boolean;
        "nativeType": 'button' | 'submit' | 'reset';
        "round": boolean;
        "size": 'small' | 'medium' | 'large';
        "type": 'default' | 'primary' | 'success' | 'danger' | 'warning' | 'dashed' | 'text' | 'link';
    }
    interface InnCalculator {
        "dark": boolean;
        "defaultValue": string;
        "height": string;
        "width": string;
    }
}
declare global {
    interface HTMLInnButtonElement extends Components.InnButton, HTMLStencilElement {
    }
    var HTMLInnButtonElement: {
        prototype: HTMLInnButtonElement;
        new (): HTMLInnButtonElement;
    };
    interface HTMLInnCalculatorElement extends Components.InnCalculator, HTMLStencilElement {
    }
    var HTMLInnCalculatorElement: {
        prototype: HTMLInnCalculatorElement;
        new (): HTMLInnCalculatorElement;
    };
    interface HTMLElementTagNameMap {
        "inn-button": HTMLInnButtonElement;
        "inn-calculator": HTMLInnCalculatorElement;
    }
}
declare namespace LocalJSX {
    interface InnButton {
        "autofocus"?: boolean;
        "circle"?: boolean;
        "color"?: string;
        "customClass"?: string;
        "disabled"?: boolean;
        "ghost"?: boolean;
        "icon"?: string;
        "iconPosition"?: 'left' | 'right';
        "loading"?: boolean;
        "nativeType"?: 'button' | 'submit' | 'reset';
        "round"?: boolean;
        "size"?: 'small' | 'medium' | 'large';
        "type"?: 'default' | 'primary' | 'success' | 'danger' | 'warning' | 'dashed' | 'text' | 'link';
    }
    interface InnCalculator {
        "dark"?: boolean;
        "defaultValue"?: string;
        "height"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "inn-button": InnButton;
        "inn-calculator": InnCalculator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "inn-button": LocalJSX.InnButton & JSXBase.HTMLAttributes<HTMLInnButtonElement>;
            "inn-calculator": LocalJSX.InnCalculator & JSXBase.HTMLAttributes<HTMLInnCalculatorElement>;
        }
    }
}
